server:
  port: 9000

spring:
  application:
    name: gateway-service

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      enabled: true
      fail-fast: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
