server:
  port: 9000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: medecin-service
          uri: lb://medecin-service
          predicates:
            - Path=/api/medecins/**
        - id: rendezvous-service
          uri: lb://rendezvous-service
          predicates:
            - Path=/api/rendezvous/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
