server:
  port: 9000  # Set your gateway port here

spring:
  application:
    name: gateway-service

  config:
    import: "optional:configserver:http://localhost:8888"  # Config server URL
    # You can also use environment variables for better flexibility, e.g.
    # import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable discovery locator
          lower-case-service-id: true  # Convert service ID to lowercase
    config:
      enabled: true  # Enable config feature
      fail-fast: false  # Don't fail if config server is unavailable

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}  # Use environment variable for Eureka URL
    register-with-eureka: true  # Register with Eureka server
    fetch-registry: true  # Fetch the registry from Eureka server
